---
title: "community-figures"
author: "K.L. Beck"
date: "6/16/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(decontam)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(robCompositions)
library(reshape)
library(stringr)
library(vegan)

options(scipen = 10)
setwd("~/Work/Code/Research-Other/milk-anomaly-detection/")

```


## Visualizations for Anomaly Detection Prelim Samples

```{r loadData}

# load microbe tables
microbePath = "./data/Milk66samples_NewFiltering_microbe_genus_DS10828562.txt"
microbes_raw = read.csv(microbePath, header = TRUE, stringsAsFactors = FALSE, sep = "\t")

microbes_reads = microbes_raw
colnames(microbes_reads) = str_remove(colnames(microbes_reads), "Cumul.reads_dt")


# order columns by sorted sample name
microbes_reads = cbind(microbes_raw$Name, microbes_reads[,order(colnames(microbes_reads))])
microbes_reads$Name = NULL
colnames(microbes_reads)[1] = "Genus_Name"

# uncomment this for raw read count export to tabular data
# write.csv(microbes_reads, "./data/read_count.txt", quote = FALSE, row.names = FALSE)


# ----- remove contaminants from lab prep ----- #
# decontam input: rows = samples, organisms = columns
drop_samples = c("Kefir*", "SequencingBlank*")
microbes_w_controls_r = dplyr::select(microbes_reads, -matches(drop_samples)) 

genera_labels_r = microbes_w_controls_r$Genus_Name
microbes_w_controls_r_t = t(data.matrix(microbes_w_controls_r[ ,-1]))
colnames(microbes_w_controls_r_t) = genera_labels_r

# extraction controls
neg_labels = grepl("Neg", row.names(microbes_w_controls_r_t))

contaminants_r = isContaminant(microbes_w_controls_r_t, neg = neg_labels, threshold = 0.5, normalize = TRUE)
# prevalence method is for negative DNA sequence controls (opposed to DNA concentration values)
# note, normalization only changes frequency
# it does not change number of on contaminants or p-values

contaminant_genera = row.names(contaminants_r)[which(contaminants_r$contaminant == TRUE)]
cat(contaminant_genera, sep = "}, \\textit{") # format for overleaf pasting

microbes_reads_decontaminated = microbes_reads[-which(microbes_reads$Genus_Name %in% contaminant_genera), ]

# uncomment this for decontaminated read count export to tabular data
# write.csv(microbes_reads_decontaminated, "./data/read_counts_decontaminated.txt", quote = FALSE, row.names = FALSE)

```

```{r computeRPM}
summaryFile = "./data/read-counts-milk-samples-controls-incl-for-RPM.txt"
macros_raw = read.table(summaryFile, sep = "\t", header = TRUE, stringsAsFactors = FALSE)

# reorder for easier merging below
macros = arrange(macros_raw, Display.TAG)


microbes_psct = microbes_reads_decontaminated

# additionally pseudo-count raw reads assigned to compute adjusted RPM
scale_const = 1000000
microbes_psct[, -1] = microbes_psct[, -1] + 1        # add one, removing all zeros

microbes_psct[,2:ncol(microbes_psct)] = sapply(2:ncol(microbes_psct), function(n) {
	microbes_psct[,n] / macros$AFTER_QC_READS[n-1] * scale_const}
	)

# Export all microbes in RPM
# old export
# write.table(microbes_psct, file = "~/Box Sync/Sequencing the Food Supply Chain Consortium - Cornell + Penn Project/Shared-Data/milk-all-samples-new-filtering-RPM-all-microbes_from_DS10828562.txt", sep = "\t", quote = FALSE, row.names = FALSE)
# decontaminated, then RPM export
# write.table(microbes_psct, file = "./data/milk_all_samples_decontam_RPM_DS10828562.txt", sep = "\t", quote = FALSE, row.names = FALSE)

```

```{r generateFeatureTable}

control_samples = c("NEG_DNAextr*", "Kefir*", "SequencingBlank*")
microbes = dplyr::select(microbes_psct, -matches(control_samples)) 
# this matches the Kraken datafile Niina added to github (note no control, keffir, etc)
colnames(microbes) = str_remove(colnames(microbes), "_ds[0-9]+")
# add preceding zeros to sample names
colnames(microbes) = str_replace(string = colnames(microbes), pattern = "_([0-9])_", replacement = "_0\\1_")

rpm_threshold = 0.1

# microbes present above rpm threshold in  **any** samples
supported_index = sapply(1:nrow(microbes), function(n) any(microbes[n,2:ncol(microbes)] > rpm_threshold))
supported_microbes_unordered = microbes[supported_index==TRUE, ]

# sort by sample name correctly
supported_microbes_ordered = supported_microbes_unordered[ , order(names(supported_microbes_unordered))]
supported_microbes_ordered$Genus_Name = NULL
supported_microbes = cbind("Genus_Name" = supported_microbes_unordered$Genus_Name, supported_microbes_ordered)

supported_microbes_melted = melt(supported_microbes)

levels(supported_microbes_melted$variable)

# old export
# write.table(supported_microbes, file = "~/Box Sync/Sequencing the Food Supply Chain Consortium - Cornell + Penn Project/Shared-Data/milk-real-samples-new-filtering-RPM-supported-microbes-only_from_DS10828562.txt", sep = "\t", quote = FALSE, row.names = FALSE)
# decontam, new export
# write.table(supported_microbes, file = "./data/milk-real-samples-decontam-RPM-supported-microbes-only_from_DS10828562.txt", sep = "\t", quote = FALSE, row.names = FALSE)

```


```{r consensusGeneraWithOutliers}

# microbes present above rpm threshold in  **all** samples
consensus_index = sapply(1:nrow(microbes), function(n) all(microbes[n,2:ncol(microbes)] > rpm_threshold))
table(consensus_index)
consensus_microbes = microbes[consensus_index==TRUE, ]
#write.table(consensus_microbes, "~/Downloads/consensus_microbes.csv", sep = ",", row.names = FALSE, quote = FALSE)
consensus_microbes_melted = melt(consensus_microbes)

# microbes present in **all** baseline samples
baseline_only = microbes %>% select(contains(c("Genus","Baseline")))
baseline_consensus_index = sapply(1:nrow(baseline_only), function(n) all(baseline_only[n,2:ncol(baseline_only)] > rpm_threshold))
table(baseline_consensus_index)
baseline_consensus_microbes = baseline_only[baseline_consensus_index==TRUE, ]
baseline_consensus_means = data.frame("Genus_Name" = baseline_consensus_microbes$Genus_Name,
									  "mean_RPM" = rowMeans(baseline_consensus_microbes[,-1])
									  )
#write.table(baseline_consensus_microbes, "~/Downloads/baseline_consensus_microbes.csv", sep = ",", row.names = FALSE, quote = FALSE)

```



```{r extractSampleMetadata}
# extract dates and sample category from sample names

treatment_names = sapply(1:ncol(supported_microbes), function(n) 
	c(paste(str_split(string = colnames(supported_microbes), pattern = "_")[[n]][1:2], collapse = "_"))
	)

sample_dates = sapply(1:ncol(supported_microbes), function(n) 
	str_split(string = colnames(supported_microbes), pattern = "_")[[n]][3]
	)

sample_details = data.frame("full_sample_name" = colnames(supported_microbes)[-1],
							"sample_dates"     = sample_dates[-1],
							"treatment_names"  = treatment_names[-1]
							)

```


## Ecological metrics - alpha diversity
```{r alpha_div}

alpha_div = data.frame("sample" = colnames(supported_microbes)[-1],
											 "nMicrobes" = sapply(2:ncol(supported_microbes), 
			 																function(x) 
																				sum(supported_microbes[ , x] >= rpm_threshold))
)

alpha_div$sample = factor(alpha_div$sample, levels = alpha_div$sample)
alpha_div$date = sapply(1:nrow(alpha_div), function(n) str_split(alpha_div$sample, pattern = "_")[[n]][3])
alpha_div$type = sapply(1:nrow(alpha_div), function(n) str_split(alpha_div$sample, pattern = "_")[[n]][1])

median_baseline_div = median(alpha_div$nMicrobes[which(grepl("Baseline*", alpha_div$sample))])

# reorder(sample, as.Date(date, format = "%y.%m.%d"))
ggplot(alpha_div, aes(x=date, y=nMicrobes, fill = type)) +
	geom_bar(stat="identity", position = "dodge") +
	ggtitle("Alpha diversity per sample") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	geom_hline(yintercept = median_baseline_div)

ggplot(alpha_div, aes(x=type, y=nMicrobes, fill = type)) + geom_violin()
ggplot(alpha_div, aes(x=type, y=nMicrobes, fill = type)) + geom_boxplot()


outlier_prefixes = c("Baseline_04", "Baseline_08", "Baseline_13", "Baseline_16", "OutsideFarm_09", "OutsideFarm_13")

alpha_div_no_outliers = alpha_div[-which(grepl(paste(outlier_prefixes, collapse = "|"), alpha_div$sample)),]

alpha_div_no_outliers %>% group_by(type) %>% summarise(mean(nMicrobes))

shannon_div = data.frame("sample" = colnames(supported_microbes)[-1],
						 "nMicrobes" = sapply(2:ncol(supported_microbes), 
						 					 function(x) 
						 					 	diversity(supported_microbes[, x]))
)

shannon_div$sample = factor(shannon_div$sample, levels = shannon_div$sample)
shannon_div$date = sapply(1:nrow(shannon_div), function(n) str_split(shannon_div$sample, pattern = "_")[[n]][3])
shannon_div$type = sapply(1:nrow(shannon_div), function(n) str_split(shannon_div$sample, pattern = "_")[[n]][1])
shannon_div$type[which(shannon_div$type == "OutsideFarm")] = "Outside Farm"
shannon_div$type[which(shannon_div$type == "TxAntibiotic")] = "Antibiotic"



# write.table(shannon_div, "~/Box Sync/Sequencing the Food Supply Chain Consortium - Cornell + Penn Project/Results/shannon_div_by_date_partial.txt", sep = "\t")

# filled in with NULL and NA where the category wasn't sampled so div can be plotted by date
shannon_div_filled_in = read.csv("./data/shannon_div_by_date_filled_in.txt", sep = "\t")



# manuscript supplemental figure - separated by dates
# TODO include outliers for date ordered supplemental
# TODO update type labels
ggplot(shannon_div_filled_in, aes(x=date, y=nMicrobes, fill = type)) +
	geom_bar(stat="identity", position = "dodge") +
	ggtitle("Shannon Index per Sample") +
	ylab("Shannon Index") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	scale_fill_manual(values = c("Baseline" = rgb(0, 0.447, 0.741), 
								 "OutsideFarm" = rgb(0.301, 0.745, 0.933), 
								 "TxAntibiotic" = rgb(0.494, 0.184, 0.556)
								 )
	)

# actual manuscript figure - FINAL
ggplot(shannon_div, aes(x=sample, y=nMicrobes, fill = type)) +
	geom_bar(stat="identity") +
	ggtitle("Shannon Index per Sample") +
	ylab("Shannon Index") +
	xlab("Sample") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
	scale_fill_manual(values = c("Baseline" = rgb(0, 0.447, 0.741), 
								 "Outside Farm" = rgb(0.301, 0.745, 0.933), 
								 "Antibiotic" = rgb(0.494, 0.184, 0.556)
								 )
					  )


shannon_div_no_outliers = shannon_div[-which(grepl(paste(outlier_prefixes, collapse = "|"), shannon_div$sample)),]
shannon_div_no_outliers$type[which(shannon_div_no_outliers$type == "Antibiotic")] = "TxAntibiotic"

shannon_div_no_outliers %>% group_by(type) %>% summarise(mean(nMicrobes))

# wilcoxon rank sum (since independently sampled)
wilcox.test(x = shannon_div_no_outliers$nMicrobes[which(shannon_div_no_outliers$type == "Baseline")],
			y = shannon_div_no_outliers$nMicrobes[which(shannon_div_no_outliers$type == "TxAntibiotic")])
wilcox.test(x = shannon_div_no_outliers$nMicrobes[which(shannon_div_no_outliers$type == "Baseline")],
			y = shannon_div_no_outliers$nMicrobes[which(shannon_div_no_outliers$type == "Outside Farm")])


# actual manuscript figure - FINAL
ggplot(shannon_div_no_outliers, aes(x=type, y=nMicrobes, fill = type)) +
	geom_violin(trim = FALSE) + 
	geom_boxplot(width = 0.2, fill  = ('transparent')) +
	ylab("Shannon Index") +
	xlab("Sample Category") +
	scale_fill_manual(values = c("Baseline" = rgb(0, 0.447, 0.741), 
								 "Outside Farm" = rgb(0.301, 0.745, 0.933), 
								 "TxAntibiotic" = rgb(0.494, 0.184, 0.556)
								 ),
					  labels = c("Baseline", "Outside Farm", "Antibiotic")
	)


```


## Microbial Community
```{r stackedMicrobesOriginal}
# colourCount = length(unique(consensus_microbes_melted$Genus_Name))
# getPalette = colorRampPalette(brewer.pal(9, "Set1"))
#  
# # consensus plots actual RPM - old manuscript version
# ggplot(consensus_microbes_melted, aes(x = variable, y = value, fill = Genus_Name)) +
# 	geom_bar(stat = "identity") + 
# 	ylab("Relative abundance") + xlab("Sample") +
# 	ggtitle(label = "Consensus genera microbial composition") +
# 	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
# 	scale_fill_manual(values = getPalette(colourCount))
# 
# # consensus plots scaled - old manuscript version
# ggplot(consensus_microbes_melted, aes(x = variable, y = value, fill = Genus_Name)) +
# 	geom_bar(stat = "identity", position = "fill") + 
# 	ylab("Relative abundance") + xlab("Sample") +
# 	ggtitle(label = "Consensus genera microbial composition") +
# 	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
# 	scale_fill_manual(values = getPalette(colourCount))

supported_microbes_no_outliers = supported_microbes %>% select(!contains(outlier_prefixes))

# sum each column
supported_microbes_col_sums = colSums(supported_microbes_no_outliers[,-1])
# get the per column threshold
other_threshold = 0.05
other_min_value = supported_microbes_col_sums * other_threshold

# if the value is less than threshold set it to zero
supported_microbes_low_abundance_zeroed = supported_microbes_no_outliers
for (i in 2:ncol(supported_microbes_low_abundance_zeroed)) {
	supported_microbes_low_abundance_zeroed[which(supported_microbes_no_outliers[,i] < other_min_value[i-1]),i] = 0
}

supported_microbes_low_abundance_zeroed_col_sums = colSums(supported_microbes_low_abundance_zeroed[,-1])
range(supported_microbes_low_abundance_zeroed_col_sums)

proportion_supported_not_other = supported_microbes_low_abundance_zeroed_col_sums / supported_microbes_col_sums
range(proportion_supported_not_other) * 100

# how much per sample is in the other category
other_values = data.frame(t(supported_microbes_col_sums - colSums(supported_microbes_low_abundance_zeroed[,-1])))
other_df = data.frame("Genus_Name" = c("Other"),
					  other_values)
rownames(other_df) = "Other"
supported_microbes_w_other = rbind(supported_microbes_low_abundance_zeroed, other_df)

max_val_rpm = sapply(1:nrow(supported_microbes_w_other), function(n)
	   max(supported_microbes_w_other[n,-1])
	   )
supported_w_other_clean = supported_microbes_w_other[which(max_val_rpm > 0), ]

supported_microbes_w_other_m = melt(supported_w_other_clean) 

supported_microbes_w_other_m$Genus_Name = relevel(factor(supported_microbes_w_other_m$Genus_Name), ref = 'Other')


ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1))
# exported as 1377 x 827 px

ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity", position = "fill") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1))
# exported as 1377 x 827 px
```


```{r stackedMicrobesUpdatedJuly}

# compute the >5% in at least one sample so that values less than 5% are still visible
# and replot 

supported_microbes_no_outliers = supported_microbes %>% select(!contains(outlier_prefixes))

# sum each column
supported_microbes_col_sums = colSums(supported_microbes_no_outliers[,-1])

# create relative percent df
supported_microbes_perc = data.frame(
	sapply(2:ncol(supported_microbes_no_outliers), function(n) 
		supported_microbes_no_outliers[,n] / supported_microbes_col_sums[n-1] * 100
	))

supported_microbes_perc = cbind(supported_microbes_no_outliers$Genus_Name, supported_microbes_perc)
colnames(supported_microbes_perc) = colnames(supported_microbes_no_outliers)

# qc on proportion
sapply(2:ncol(supported_microbes_perc), function(n)
	sum(supported_microbes_perc[,n]))

# get the any >= 5% table
gtr5perc_index = sapply(1:nrow(supported_microbes_perc), function(n) any(supported_microbes_perc[n,2:ncol(supported_microbes_perc)] >= 5))
genera_gtr5perc = supported_microbes_perc$Genus_Name[gtr5perc_index==TRUE]

# then get the microbe names for the other
genera_other = supported_microbes_perc$Genus_Name[gtr5perc_index==FALSE]

# sum RPM for "other" category
other_sum_per_column = colSums(
	supported_microbes_no_outliers[which(supported_microbes_no_outliers$Genus_Name %in% genera_other),
								   2:ncol(supported_microbes_no_outliers)]
)

supported_microbes_w_other_v2 = supported_microbes_no_outliers[which(supported_microbes_no_outliers$Genus_Name %in% genera_gtr5perc), ]

supported_microbes_w_other_v2_1 = rbind(c(0, other_sum_per_column), supported_microbes_w_other_v2)
supported_microbes_w_other_v2_1$Genus_Name[1] = "Other"
rownames(supported_microbes_w_other_v2_1)[1] = "Other"

# calculate the range the "predominant" microbes account for
range(colSums(supported_microbes_w_other_v2_1[-which(supported_microbes_w_other_v2_1$Genus_Name == "Other"),-1]) / colSums(supported_microbes_w_other_v2_1[,-1]) * 100)

# compare microbe table with other summed versus complete microbe table
sumComparisonFullVsOther = data.frame("othered" = colSums(supported_microbes_w_other_v2_1[,-1]),
									  "regular" = colSums(supported_microbes_no_outliers[,-1]))
table(sumComparisonFullVsOther$othered - sumComparisonFullVsOther$regular)
# margins of rounding, these are equivalent dataframes


supported_microbes_w_other_m = melt(supported_microbes_w_other_v2_1) 

genus_order_mean = order(rowMeans(supported_microbes_w_other_v2_1[,-1]), decreasing = TRUE)
manuscript_preferred_order = supported_microbes_w_other_v2_1$Genus_Name[genus_order_mean]
manuscript_preferred_order = manuscript_preferred_order[-which(manuscript_preferred_order == "Other")]
manuscript_preferred_order = c(manuscript_preferred_order, "Other")
# supported_microbes_w_other_m$Genus_Name = relevel(factor(supported_microbes_w_other_m$Genus_Name), ref = 'Other')

supported_microbes_w_other_m$Genus_Name = factor(supported_microbes_w_other_v2_1$Genus_Name, 
												 levels = manuscript_preferred_order
												 )



ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1))
# exported as 1377 x 827 px

ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity", position = "fill") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1))
# exported as 1377 x 827 px

# color fussiness
# https://stackoverflow.com/questions/15282580/how-to-generate-a-number-of-most-distinctive-colors-in-r


colourCount = length(unique(supported_microbes_w_other_m$Genus_Name))
getPalette = colorRampPalette(brewer.pal(12, "Paired"))
orig_colors = getPalette(colourCount)
orig_colors[9] = "#9A4979"
orig_colors[11] = "#FEA594"

ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	scale_fill_manual(values = orig_colors)
# exported as 1377 x 827 px

ggplot(supported_microbes_w_other_m, aes(x = variable, y = value, fill = Genus_Name)) +
	geom_bar(stat = "identity", position = "fill") + 
	ylab("Relative abundance") + xlab("Sample") +
	ggtitle(label = "Supported genera microbial composition") +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	scale_fill_manual(values = orig_colors)
# exported as 1377 x 827 px
```


```{r consensusGeneraNoOutliers}

# microbes present in **all** samples
consensus_index_correct = sapply(1:nrow(supported_microbes_no_outliers), function(n) all(supported_microbes_no_outliers[n,2:ncol(supported_microbes_no_outliers)] > rpm_threshold))
table(consensus_index_correct)
consensus_microbes_correct = supported_microbes_no_outliers[consensus_index_correct==TRUE, ]

# write.table(consensus_microbes_correct, "~/Downloads/consensus_microbes_no_outliers.csv", sep = ",", row.names = FALSE, quote = FALSE)

# microbes present in **all baseline** samples
baseline_only_no_outliers = supported_microbes_no_outliers %>% select(contains(c("Genus","Baseline")))
baseline_consensus_index_correct = sapply(1:nrow(baseline_only_no_outliers), function(n) all(baseline_only_no_outliers[n,2:ncol(baseline_only_no_outliers)] > rpm_threshold))
table(baseline_consensus_index_correct)
baseline_consensus_microbes_correct = baseline_only_no_outliers[baseline_consensus_index_correct==TRUE, ]

```


## Ecological metrics - beta diversity

```{r beta_div_all_samples}
# ALL SAMPLES
rownames(supported_microbes) = supported_microbes$Genus_Name
ad = aDist(t(supported_microbes[,-1]))
# write.table(as.matrix(ad), "~/Box Sync/Sequencing the Food Supply Chain Consortium - Cornell + Penn Project/Results/aitchison-distance-matrix-all-samples.txt", sep="\t")
hc_complete = hclust(ad, method = "complete")
hc_average  = hclust(ad, method = "average")
# clustering method could be complete (default) or any other 
# http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.876.3979&rep=rep1&type=pdf

# par(mfrow=c(2,1))
plot(hc_complete, main="Aitchison distance- Complete clustering", ylab="Distance", xlab="Sample Identifier", hang = -1)
plot(hc_average,  main="Aitchison distance- Average clustering", ylab="Distance", xlab="Sample Identifier", hang = -1)
# hang = -1 recommended by bala

# as recommended by Gloor froniers in microbiology supplement 2016
# https://github.com/ggloor/Frontiers_2017/blob/master/Frontiers_supplement.Rmd
# coloring from https://rpubs.com/gaston/dendrograms
# make the dendrogram
hc <- as.dendrogram(hclust(ad, method="ward.D2"))
hcd <- hclust(ad, method="ward.D2")
# function to get color labels
colLab <- function(n) {
    if (is.leaf(n)) {
        a <- attributes(n)
        #labCol <- labelColors[clusMember[which(names(clusMember) == a$label)]]
        # MFMB-04, 20, 38 are all host contaminated
        # MFMB- <80 are the first supplier
        # MFMB- >=80 are the second supplier
        labCol <- if (grepl("Outside*", a$label) == TRUE ) "red" else if (grepl("TxAntibiotic", a$label) == TRUE ) "#339933" else "#6699FF"
        attr(n, "nodePar") <- c(a$nodePar, lab.col = labCol)
    }
    n
}


# using dendrapply, manuscript version
clusDendro = dendrapply(hc, colLab)
par(mar = c(11, 2, 2, 2))
plot(clusDendro, main="Beta diversity clustering by sample (Aitchison distance)", ylab="Aitchison distance")
legend("topright", 
     legend = c("Baseline" , "Tx Antibiotic" , "Outside Farm"), 
     col = c("#6699FF", "#339933", "red"), 
     pch = 20, bty = "n",  pt.cex = 1.5, cex = 1, 
     text.col = c("#6699FF", "#339933", "red"), horiz = FALSE, inset = c(0.05, 0.03))
```


```{r beta_div_outliers_removed}
rownames(supported_microbes_no_outliers) = supported_microbes_no_outliers$Genus_Name

ad = aDist(t(supported_microbes_no_outliers[,-1]))
# write.table(as.matrix(ad), "~/Box Sync/Sequencing the Food Supply Chain Consortium - Cornell + Penn Project/Results/aitchison-distance-matrix-outliers-removed.txt", sep="\t")
hc_complete = hclust(ad, method = "complete")
hc_average  = hclust(ad, method = "average")
# clustering method could be complete (default) or any other 
# http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.876.3979&rep=rep1&type=pdf

# par(mfrow=c(2,1))
plot(hc_complete, main="Aitchison distance- Complete clustering", ylab="Distance", xlab="Sample Identifier", hang = -1)
plot(hc_average,  main="Aitchison distance- Average clustering", ylab="Distance", xlab="Sample Identifier", hang = -1)
# hang = -1 recommended by bala

# as recommended by Gloor froniers in microbiology supplement 2016
# https://github.com/ggloor/Frontiers_2017/blob/master/Frontiers_supplement.Rmd
# coloring from https://rpubs.com/gaston/dendrograms
# make the dendrogram
hc <- as.dendrogram(hclust(ad, method="ward.D2"))
hcd <- hclust(ad, method="ward.D2")
# function to get color labels
colLab <- function(n) {
    if (is.leaf(n)) {
        a <- attributes(n)
        #labCol <- labelColors[clusMember[which(names(clusMember) == a$label)]]
        # MFMB-04, 20, 38 are all host contaminated
        # MFMB- <80 are the first supplier
        # MFMB- >=80 are the second supplier
        labCol <- if (grepl("Outside*", a$label) == TRUE ) "#4DBEEE" else if (grepl("TxAntibiotic", a$label) == TRUE ) "#7E2F8E" else "#0072BD"
        attr(n, "nodePar") <- c(a$nodePar, lab.col = labCol)
    }
    n
}

# "Baseline" = rgb(0, 0.447, 0.741), #0072BD
# "Outside Farm" = rgb(0.301, 0.745, 0.933), #4DBEEE 
# "Antibiotic" = rgb(0.494, 0.184, 0.556), #7E2F8E


# using dendrapply, updated w no outliers
clusDendro = dendrapply(hc, colLab)
par(mar = c(11, 2, 2, 2))
plot(clusDendro, main="Beta diversity clustering by sample (Aitchison distance, outliers removed)", ylab="Aitchison distance")
legend("topright", 
     legend = c("Baseline" , "Outside Farm", "Antibiotic"), 
     col = c("#0072BD", "#4DBEEE", "#7E2F8E"), 
     pch = 20, bty = "n",  pt.cex = 1.5, cex = 1, 
     text.col = c("#0072BD", "#4DBEEE", "#7E2F8E"), horiz = FALSE, inset = c(0.05, 0.03))
```


```{r beta_div_baseline_only}
baseline_samples = supported_microbes %>% select(contains("Baseline"))
rownames(baseline_samples) = supported_microbes$Genus_Name
baseline_samples_meta = data.frame("sample_name" = colnames(baseline_samples), 
								   "date" = str_extract(colnames(baseline_samples), "2018\\.[0-9\\.]+")
)

ad = aDist(t(baseline_samples[,-1]))
hc_complete = hclust(ad, method = "complete")
hc_average  = hclust(ad, method = "average")
# clustering method could be complete (default) or any other 
# http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.876.3979&rep=rep1&type=pdf

par(mfrow=c(2,1))
plot(hc_complete, 
	 main="Aitchison distance- Complete clustering, baseline only", 
	 ylab="Distance", xlab="Sample Identifier", hang = -1
	 )
plot(hc_average,  
	 main="Aitchison distance- Average clustering, baseline only", 
	 ylab="Distance", xlab="Sample Identifier", hang = -1
	 )
# hang = -1 recommended by bala

# as recommended by Gloor froniers in microbiology supplement 2016
# https://github.com/ggloor/Frontiers_2017/blob/master/Frontiers_supplement.Rmd
# coloring from https://rpubs.com/gaston/dendrograms
# make the dendrogram
hc <- as.dendrogram(hclust(ad, method="ward.D2"))
hcd <- hclust(ad, method="ward.D2")
# function to get color labels

plot(hcd,  
	 main="Aitchison distance- Ward.D2 clustering, baseline only", 
	 ylab="Distance", xlab="Sample Identifier", hang = -1
	 )

```
